all: clear driver1 driver2

clear:
	@clear

driver1:
	@g++ driver1.cpp AbstractTetris.cpp TetrisArray1D.cpp TetrisVector.cpp TetrisAdapter.hpp -o main1.out	
	@./main1.out

driver2:
	@g++ driver2.cpp AbstractTetris.cpp TetrisArray1D.cpp TetrisVector.cpp TetrisAdapter.hpp -o main2.out	
	@./main2.out
